In [ ]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib as pyplot


In [ ]:
x=[8.0, 1, 2.5, 4, 28.0]
x_with_nan=[8.0, 1, 2.5,math.nan, 4, 28.0]

In [ ]:
x

[8.0, 1, 2.5, 4, 28.0]

In [ ]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [ ]:
y, y_with_nan=np.array(x), np.array(x_with_nan)
z, z_with_nan=pd.Series(x), pd.Series(x_with_nan)

In [ ]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [ ]:
y_with_nan

array([ 8. ,  1. ,  2.5,  nan,  4. , 28. ])

In [ ]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [ ]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

Średnia arytnetyczna

In [ ]:
mean_=sum(x)/len(x)

In [ ]:
mean_

8.7

In [ ]:
mean= statistics.mean(x)
mean_

8.7

In [ ]:
mean_=statistics.fmean(x)
mean_

8.7

średnia ważona

In [ ]:
w=[0.1, 0.2, 0.3, 0.25, 0.15]
wmean=sum(w[i]*x[i] for i in range(len(x)))/sum(w)
wmean

6.95

In [ ]:
wmean= sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
wmean

6.95

In [ ]:
y,z, w=np.array(x), pd.Series(x), np.array(w)
wmean=np.average(y, weights=w)
wmean

6.95

In [ ]:
wmean=np.average(z, weights=w)
wmean


6.95

In [ ]:
(w * y).sum()/w.sum()

6.95

średnia harmoniczna

In [ ]:
hmean = len(x)/sum(1/item for item in x)
hmean

2.7613412228796843

In [ ]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [ ]:
statistics.harmonic_mean(x_with_nan)

nan

In [ ]:
statistics.harmonic_mean([1,0,2])

0

In [ ]:
statistics.harmonic_mean([1,2,-2])

StatisticsError: harmonic mean does not support negative values

In [ ]:
scipy.stats.hmean(y)

2.7613412228796843

In [ ]:
scipy.stats.hmean(z)

2.7613412228796843

średnia geometryczna

In [ ]:
gmean= 1
for item in x:
    gmean*=item


In [ ]:
gmean**=1/len(x)
gmean

4.677885674856041

mediana

In [ ]:
n= len(x)
if n%2:
    median_=sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index=sorted(x), round(0.5*n)

In [ ]:
median_

4

In [ ]:
median_=statistics.median(x)
median_

4

In [ ]:
median_=statistics.median(x[:-1])
median_

3.25

In [ ]:
statistics.median_low(x[:-1])

2.5

In [ ]:
statistics.median_high(x[:-1])

4

In [ ]:
statistics.median(x_with_nan)

6.0

In [ ]:
statistics.median_low(x_with_nan)

4

In [ ]:
statistics.median_high(x_with_nan)

8.0

Dwa elementy w śdrodku to 4 i 8.0

In [ ]:
median_ = np.median(y)
median_

4.0

In [ ]:
median_ = np.median(y[:-1])
median_

3.25

In [ ]:
np.nanmedian(y_with_nan)

4.0

In [ ]:
np.nanmedian(y_with_nan[:-1])

3.25

In [ ]:
z.median()

4.0

In [ ]:
z_with_nan.median()

4.0

Tryb

In [ ]:
u= [2,3,2,8,12]
mode_=max((u.count(item), item) for item in set(u))[1]

In [ ]:
mode_


2

In [ ]:
mode_=statistics.mode(u)
mode_

2

In [ ]:
mode_=statistics.multimode(u)
mode_

[2]

In [ ]:
v=[ 12, 15, 12, 15, 21, 15, 12]
statistics.mode(v)

12

In [ ]:
statistics.multimode(v)

[12, 15]

In [ ]:
statistics.mode([2, math.nan, 2])

2

In [ ]:
statistics.multimode([2, math.nan, 2])

[2]

In [ ]:
statistics.mode([2, math.nan, 0, math.nan, 5])

nan

In [ ]:
statistics.multimode([2, math.nan, 0, math.nan, 5])

[nan]

In [ ]:
u,v = np.array(u), np.array(v)
mode_=scipy.stats.mode(u)
mode_

ModeResult(mode=2, count=2)

In [ ]:
mode_=scipy.stats.mode(v)
mode_

ModeResult(mode=12, count=3)

In [ ]:
mode_.mode

12

In [ ]:
mode_.count

3

In [ ]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2,2,math.nan,2,math.nan])

In [ ]:
u.mode()

0    2
dtype: int64

In [ ]:
v.mode()

0    12
1    15
dtype: int64

In [ ]:
w.mode()

0    2.0
dtype: float64

Wariancja


In [ ]:
n= len(x)
mean_=sum(x)/n
var_=sum((item-mean_)**2 for item in x)/(n-1)
var_

123.19999999999999

In [ ]:
var_=statistics.variance(x)
var_

123.2

In [ ]:

statistics.variance(x_with_nan)

ValueError: cannot convert NaN to integer ratio

In [ ]:
var_= np.var(y, ddof=1)
var_

123.19999999999999

In [ ]:
var_= v.var(ddof=1)
var_

10.285714285714286

In [ ]:
np.var(y_with_nan, ddof=1)

nan

In [ ]:
y_with_nan.var(ddof=1)

nan

In [ ]:
np.nanvar(y_with_nan, ddof=1)

123.19999999999999

In [ ]:
z.var(ddof=1)

123.19999999999999

In [ ]:
z_with_nan.var(ddof=1)

123.19999999999999

Odchylenie standardowe

In [ ]:
std_ = var_ ** 0.5
std_

3.2071349029490928

In [ ]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [ ]:
np.std(y,ddof=1)

11.099549540409285

In [ ]:
y.std(ddof=1)

11.099549540409285

In [ ]:
np.std(y_with_nan, ddof=1)

nan

In [ ]:
y_with_nan.std(ddof=1)

nan

In [ ]:
np.nanstd(y_with_nan, ddof=1)

11.099549540409285

In [ ]:
z.std(ddof=1)

11.099549540409285

In [ ]:
z_with_nan.std(ddof=1)

11.099549540409285

Skośność

In [ ]:
x= [ 8.0, 1, 2.5, 4, 28.0]
n= len(x)
mean_=sum(x)/n
var_ = sum((item-mean_)**2 for item in x)/(n-1)
std_=var_**0.5
skew_ = (sum((item-mean_)**3 for item in x)*n/((n-1)*(n-2)*std_**3))

skew_


1.9470432273905929

Skośność jest dodatnia


In [ ]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [ ]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [ ]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
z.skew()

1.9470432273905924

In [ ]:
z_with_nan.skew()

1.9470432273905924

Kurtoza

In [ ]:
from scipy.stats import kurtosis

In [ ]:
print(kurtosis(x, axis=0, bias=True))

-0.030495095281138695


Kurtoza zbioru x: -0.030495095281138695



Percentyl

In [ ]:
x= [-5.0, -1.1, 0.1, 2.0, 9.0, 12.8, 21.0, 25.8, 41.0]
statistics.quantiles(x,n=2)

[9.0]

In [ ]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 9.0, 21.0]

In [ ]:
y= np.array(x)
np.percentile(y,5)

-3.44

In [ ]:
np.percentile(y,95)

34.919999999999995

In [ ]:
np.percentile(y, [25,50, 75])

array([ 0.1,  9. , 21. ])

In [ ]:
np.median(y)

9.0

In [ ]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  9. , 12.8, 21. , 25.8, 41. ])

In [ ]:
np.nanpercentile(y_with_nan, [25,50,75])

array([ 0.1,  9. , 21. ])

In [ ]:
np.quantile(y,0.05)

-3.44

In [ ]:
np.quantile(y,0.95)

34.919999999999995

In [ ]:
np.quantile(y,[0.25,0.5,0.75])

array([ 0.1,  9. , 21. ])

In [ ]:
np.quantile(y_with_nan,[0.25,0.5,0.75])

array([nan, nan, nan])

In [ ]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-3.44

In [ ]:
z.quantile(0.95)

34.919999999999995

In [ ]:
z.quantile([0.25,0.5,0.75])

0.25     0.1
0.50     9.0
0.75    21.0
dtype: float64

In [ ]:
z_with_nan.quantile([0.25,0.5,0.75])

0.25     0.1
0.50     9.0
0.75    21.0
dtype: float64

Zakres

In [ ]:
np.ptp(y)

46.0

In [ ]:
np.ptp(z)

46.0

In [ ]:
np.ptp(y_with_nan)

nan

In [ ]:
np.ptp(z_with_nan)

nan

In [ ]:
np.amax(y) - np.amin(y)

46.0

In [ ]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [ ]:
y.max() - y.min()

46.0

In [ ]:
z.max() - z.min()

46.0

In [ ]:
z_with_nan.max() - z_with_nan.min()

46.0

In [ ]:
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [ ]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

Podsumowanie statystyk opisowych

In [ ]:
result= scipy.stats.describe(y, ddof=1, bias=False)

In [ ]:
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.733333333333333, variance=227.95749999999998, skewness=0.9027347498723649, kurtosis=0.13502711451354799)

In [ ]:
result.nobs

9

In [ ]:
result.minmax[0]

-5.0

In [ ]:
result.minmax[1]

41.0

In [ ]:
result.mean

11.733333333333333

In [ ]:
result.variance

227.95749999999998

In [ ]:
result.skewness

0.9027347498723649

In [ ]:
result.kurtosis

0.13502711451354799

In [ ]:
result= z.describe()
result

count     9.000000
mean     11.733333
std      15.098261
min      -5.000000
25%       0.100000
50%       9.000000
75%      21.000000
max      41.000000
dtype: float64

In [ ]:
result['mean']

11.733333333333333

In [ ]:
result['std']

15.09826148932386

In [ ]:
result['min']

-5.0

In [ ]:
result['max']

41.0

In [ ]:
result['25%']

0.1

In [ ]:
result['50%']

9.0

In [ ]:
result['75%']

21.0